### ISSUE TITLE
Implement RTK Query in Next.js 13 to provide functionality of loading state tracking, caching, and optimistic updates.

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#119]
#### Description:

Implementing RTK Query offers a structured approach to managing data fetching and store state in the application and facilitates features like loading state tracking, caching, and optimistic updates ultimately leading to a smoother and more responsive user experience.

**User Story: Authentication State Management**

**As**  a developer,
**I want** to implement RTK Query API in Next.js 13 app to demo user authentication
**so that** loading state tracking, optimistic updates, caching, are handled during the data fetching process
**and this help** improve the user experience 

#### Acceptance Criteria:

**Scenario 1: Implementing RTK Query**

- **Given** that I am a developer working on Next.js 13 app dir application,
- **When** I set up the RTK Query for mock authentication,
- **Then** I expect to be able to define an API slice with endpoints for login and user data retrieval.

**Scenario 2: Mock Authentication**

- **Given** that I have implemented the RTK Query endpoints for login and user data retrieval,
- **When** a user attempts to log in with credentials,
- **Then** I want to simulate a successful login by returning a mock user object and a token from the login endpoint.

**Scenario 3: Loading State Tracking**

- **Given** that authentication API request is in progress,
- **When** data is being fetched
- **Then** I want to track the loading state to display loading indicators to the user.

**Scenario 4: Caching**

- **Given** that a user's data is retrieved,
- **When** subsequent requests are made for the same data,
- **Then** I want to utilize the RTK Query's caching mechanism to avoid unnecessary network requests and use the cached data instead.

**Acceptance Criteria:**

- RTK Query is successfully integrated into our Next.js application.
- Mock authentication endpoints for login and user data retrieval are defined and functional.
- User data is cached and retrieved from the cache when applicable.
- Loading state is tracked and displayed appropriately in the user interface.
- Error handling is in place for API requests.
- A demo or proof-of-concept of mock authentication with RTK Query is available for review and testing.

#### Development Checklist:

- [x] Redux slice actions and reducers for authentication are implemented
- [x] UI components are updated to reflect loading states, optimistic updates, and error handling during authentication.
- [x] Cached authentication data is stored and used appropriately
- [x] Authentication-related loading states are displayed to the user as needed.
- [x]  Any potential errors during authentication are handled gracefully with error messages to the user.
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-
