### ISSUE TITLE
Registration Part II - Missing URL tracking issue

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#2121]
As we build out Registration 2 some user stories we implement may have links to URLs that we don't have yet. This issue is to track them and ensure they are added at a later date.

### Operation Registration - New Entrant Operation

~- Needs both `Application form templates` for `On or before March 31, 2024` and `On or after April 1, 2024`~
~- Update the `newEntrantOperationUiSchema` in `newEntrantOperation.ts` with the correct URLs~

This was completed in https://github.com/bcgov/cas-registration/issues/2426

### Operation Registration - Success screen
- Latest design should be like: https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=21269-5898&t=rvWmyldLWE8I4v9n-4
And clicking `Link to Form` should take the user to: https://submit.digital.gov.bc.ca/app/form/submit?f=d26fb011-2846-44ed-9f5c-26e2756a758f

**Comment by patriciarussellCAS** [comment]
Adding a note that the New Entrant form will be uploaded to the BC Government public website. Location and specific URL are still being determined. We can confirm closer to Prod.

**Comment by Sepehr-Sobhani** [comment]
Hey @zoeyli-46 ! Below is our current implementation. We already have a button to return the user to the registration dashboard. Given this, what would be the best link for the 'Report a Change' button?
 
![Image](https://github.com/user-attachments/assets/dfc126c2-5cda-457c-bc53-289b39a81c84)

**Comment by patriciarussellCAS** [comment]
@Sepehr-Sobhani when they click on Report a change I believe they should be redirected to the transfer page - here's the wireframe https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=23217-5751&t=yGVJfW0aNzJ3AMew-4

**Comment by Sepehr-Sobhani** [comment]
> [@Sepehr-Sobhani](https://github.com/Sepehr-Sobhani) when they click on Report a change I believe they should be redirected to the transfer page - here's the wireframe https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=23217-5751&t=yGVJfW0aNzJ3AMew-4

@zoeyli-46 suggested that it would be better UX to directly link the user to the form instead of the "report a change" page.

**Comment by fviduya** [comment]
I have tested this in the DEV environment, [here is the test document for reference](https://buttoninc-my.sharepoint.com/:w:/g/personal/francesca_button_is/ERZe7Wc69EJImNCUvWUO4mYB0kBU1ewKstivSnUB7rIFHw?e=j6EdeJ).

I can verify that: 
- [x] The submission page is similar to the wireframe in the description
- [x] The submission page allows the user to report an event using the link specified in the wireframe 
- [x] Clicking the `Back to Dashboard` navigates back to the registration dashboard - this should navigate back to the main dashboard but this will be fixed in #2568 

The functionality looks good, however, I recommend changing the link text from `Link to Form` to something more descriptive such as `Report an Event` or `Submit a Report` to improve accessibility.  

Moving to Pending PO for review of test and notes. Thank you!

**Comment by vesselak** [comment]
Reviewed the QA documentation and tested in dev. Accepting ticket with the deficiency to be fixed in #2568 
@fviduya please create a ticket for the suggested change link to form to be replaced with more accessible language and leave in backlog for priority post prod release.

**Comment by zoeyli-46** [comment]
Hey @fviduya great flag! lets call it "Report an Event" because we use this language on the other pages, so it will be consistent
