### ISSUE TITLE
Registration Wording updates: additions and edits

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2147]
- [ ] Contacts tile description needs to be updated to what is written on the [figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=22844-976&t=rQ50kjN6MMzGoohW-4) Addressed in ticket #2608 
- [ ] Registration Tile: Still says "Submit BORO ID application" - needs to be updated. [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=21269-5893&t=ccI6nsQrfaNlSsbJ-4) Addressed in ticket #2609
- [ ] On the Add contact page, update the "note" on the bottom of the page as written on the [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18028-7473&t=7z5z963z7R4f8By0-4) Addressed in ticket #2610
- [ ] Facility page: add page description according to [figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7817-186&t=N7kfCCpaiPRD0Xo9-4)Addressed in ticket #2611
- [ ] Registration Purpose description for the opt-in should be: Note: An Opted-in Operation is an industrial operation that produces a regulated product and emits less than 10,000 tCO2e per year. These operations may apply to voluntarily participate in the B.C. OBPS. This option should be selected if your operation has already been designated as an Opted-In Operation, OR if your operation is registering and applying to be an Opted-In Operation for the first time. Addressed in ticket #2612
- [ ] [Opt-in application ](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=13653-2443&t=7z5z963z7R4f8By0-4) sentence needs to be updated from "Does this operation produce a regulated product listed in Table 1 of Schedule A.1 of the GGERR?" to 'Does this operation produce a regulated product listed in Table 2 of Schedule A.1 of the GGERR?' Addressed in ticket #2613

**Comment by zoeyli-46** [comment]
Hey @patriciarussellCAS should some of these be prioritized in next sprint since they were mentioned from the UAT results? some of its just simple changes like changing the text from table 1 to table 2 on the opt in application

**Comment by patriciarussellCAS** [comment]
Thanks @zoeyli-46 - I think the the 4th item, the new entrant or opt-in application should be the priority. The rest seem like design backlog items. 
Also, just noting that the figma link for the 3rd item, facility page - doesn't seem to be linked properly.

**Comment by zoeyli-46** [comment]
@patriciarussellCAS Moved it to a new ticket #2545 https://github.com/orgs/bcgov/projects/123/views/16?filterQuery=&pane=issue&itemId=89447407&issue=bcgov%7Ccas-registration%7C2545 

edited figma link for facility page

**Comment by zoeyli-46** [comment]
Closing this ticket because each item is now in its own ticket
