### ISSUE TITLE
Remove extra sub-dashboards

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-registration#2568]
### Context
When an external user completes a registration and clicks the "return to dashboard" button, they are taken to this page:

![Image](https://github.com/user-attachments/assets/03c7f14a-4ea7-4187-9a01-6f7706d4d7c5)

Users in testing have expressed confusion at being taken here instead of the main dashboard. This is mostly due to the fact that they didn't click through this dashboard in the first place, so this is the first time they are seeing the page and it is unexpected. 

This was also identified as an issue during Accessibility testing

### Task
- [ ] Remove Administration, Reporting, and Registration dashboards for external user
- [ ] Remove the "transfers" dashboard for internal users 
- [ ] Remove the hover state on the main BCIERS dashboard tiles, so it doesn't appear clickable for external user
Example: when hovering over the tile, it has a gray shadow to denote that its clickable, remove it
<img width="346" alt="Image" src="https://github.com/user-attachments/assets/00ca5e52-5bde-45cf-876c-e4bea4f016e7" />

For reference, remove these dashboards:
<img width="638" alt="Image" src="https://github.com/user-attachments/assets/020af6d1-0899-4116-9072-911cf0b52e47" />

### Acceptance Criteria
Given that I am an EXTERNAL USER on the main BCIERS dashboard
The Administration, Registration, and Reporting tiles are NOT clickable
If I click on the tile, it will NOT take me to a second dashboard 
I must click on the individual links within the tiles 

- [ ] The Administration dashboard should still exist for Internal Users

**Comment by patriciarussellCAS** [comment]
@fviduya I think this is a good ticket for you to take on, but doesn't need to be prioritized this sprint, given all the other work happening. 
I will note, that this issue occurs for all the modules and I don't think we have a ticket yet for Admin or Reporting.

**Comment by zoeyli-46** [comment]
I have included removal of all subdashboards Administration, Reporting, Compliance and Registration in this ticket, but can separate them into their own individual tickets. might make sense for it to be done all at once so users are not confused why there is a subdashboard for registration but not for administration

**Comment by patriciarussellCAS** [comment]
Thanks @zoeyli-46 - I have heard from Compliance that they would prefer to keep the sub-dashboards in that module, so let's remove those. 
We talked about having a team discussion about this issue but don't believe it's been scheduled yet. I'll tag @patrickisaac so he can confirm. 
We need to understand how much work is involved (for example, how many ways can people navigates to these dashboards?) and what the risks are of removing these sub-dashboards.

**Comment by patrickisaac** [comment]
@patriciarussellCAS @zoeyli-46 - I have not set this meeting up yet. Do we know who would be included in this discussion in addition to @vesselak so I can schedule this?

**Comment by zoeyli-46** [comment]
I suggest having Shon because Shon is currently building out the sub-dashboard/did work on the dashboard, also Andrea for the reg/admin side. would you agree Patricia?

**Comment by zoeyli-46** [comment]
Closing this ticket, based on today's conversation with POs and reg/reporting devs, the subdashboards will be kept for administration and compliance. For consistency, the subdashboard for registration will be kept too.
